package com.dim.cls.util;

public enum Grade {

	GRADE1,GRADE2,GRADE3,GRADE4,GRADE5,GRADE6,GRADE7,GRADE8,GRADE9,GRADE10,
	ORDINARY_LEVEL,ADVANCED_LEVEL,THREE_YEAR_DEGREE,FOUR_YEAR_DEGREE,
	DIPLOMA
	
}
